### PR TITLE
Release Maven packages [DEVOPS-1295]

### PR DESCRIPTION
**Pull request by miharugelj**
https://celtra.atlassian.net/browse/DEVOPS-1295

### CODE REVIEW

**Comment by dejanceltra** [comment]
@miharugelj one test is failing: https://github.com/celtra/finagle/actions/runs/6233342981/job/16918402750?pr=5

Is this the issue from the upstream repo or did we break something?

**Review by dejanceltra — COMMENTED** [review]
Can you please test that this really works? For example you can comment out that release job is only triggered on tags, so that it get's trigger on push.

**Comment by miharugelj** [comment]
> @miharugelj one test is failing: https://github.com/celtra/finagle/actions/runs/6233342981/job/16918402750?pr=5
> 
> Is this the issue from the upstream repo or did we break something?

Almost impossible that we broke anything in this PR related to app code.

**Comment by dejanceltra** [comment]
@miharugelj fyi you will need to allow GHA access to `files.celtra.com/maven/` here: https://github.com/celtra/mab-prod-infra/blob/9da55f335452fd8b0542cce534cc9866f595d84a/modules/files_bucket/main.tf#L48

**Comment by miharugelj** [comment]
> @miharugelj fyi you will need to allow GHA access to `files.celtra.com/maven/` here: https://github.com/celtra/mab-prod-infra/blob/9da55f335452fd8b0542cce534cc9866f595d84a/modules/files_bucket/main.tf#L48

@dejanceltra You are right. Thanks! Release test already failed with `An error occurred (AccessDenied) when calling the PutObject operation: Access Denied`

**Comment by miharugelj** [comment]
@dejanceltra Looks like release job works.
```
aws-vault exec <profile> -- aws s3 ls <host>/maven/com/twitter/finagle-http_2.12/22.12.1/ 
2023-09-21 09:20:30     491308 finagle-http_2.12-22.12.1.jar
2023-09-21 09:20:32         41 finagle-http_2.12-22.12.1.jar.sha1
2023-09-21 09:20:34      13125 finagle-http_2.12-22.12.1.pom
2023-09-21 09:20:36         41 finagle-http_2.12-22.12.1.pom.sha1
```

**Review by dejanceltra — APPROVED** [review]

**Comment by dejanceltra** [comment]
@miharugelj Uncomment `if` and merge.

**Comment by miharugelj** [comment]
@dejanceltra Sounds like it is is working
```
services/ads/bin/build 
Launching sbt from /app/build/shared/scala/sbt1/sbt-launch-1.8.0/sbt/bin/sbt-launch.jar
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -XX:ErrorFile=/app-var/tmp/java_error_%p.log -Djava.net.preferIPv4Stack=true -Dsun.net.inetaddr.ttl=0 -Dnet.snowflake.jdbc.ocspResponseCacheDir=/app-var/tmp/snowflake -Dnet.snowflake.jdbc.temporaryCredentialCacheDir=/app-var/tmp/snowflake -Dio.netty.native.workdir=/app-var
[info] welcome to sbt 1.8.0 (Ubuntu Java 11.0.20.1)
[info] loading settings for project app-build from build.sbt,plugins.sbt ...
[info] loading project definition from /app/project
[info] loading settings for project root from build.sbt ...
[info] resolving key references (24115 settings) ...
[info] set current project to mab (in build file:/app/)
[info] Updating 
https://nexus.celtra.com/repository/maven/com/twitter/finagle-http_2.12/22.12.1/finagle-http_2.12-22.12.1.pom
  100.0% [##########] 12.8 KiB (13.9 KiB / s)
https://nexus.celtra.com/repository/maven/com/twitter/finagle-base-http_2.12/22.12.1/finagle-base-http_2.12-22.12.1.pom
  100.0% [##########] 15.9 KiB (26.4 KiB / s)
https://nexus.celtra.com/repository/maven/com/twitter/finagle-netty4-http_2.12/22.12.1/finagle-netty4-http_2.12-22.12.1.pom
  100.0% [##########] 14.9 KiB (22.5 KiB / s)
https://nexus.celtra.com/repository/maven/com/twitter/finagle-netty4_2.12/22.12.1/finagle-netty4_2.12-22.12.1.pom
  100.0% [##########] 21.7 KiB (52.5 KiB / s)
https://nexus.celtra.com/repository/maven/com/twitter/finagle-core_2.12/22.12.1/finagle-core_2.12-22.12.1.pom
  100.0% [##########] 32.6 KiB (58.9 KiB / s)
https://nexus.celtra.com/repository/maven/io/netty/netty-codec-haproxy/4.1.78.Final/netty-codec-haproxy-4.1.78.Final.pom
  100.0% [##########] 1.8 KiB (4.3 KiB / s)
[info] Resolved  dependencies
[info] Fetching artifacts of 
https://nexus.celtra.com/repository/maven/io/netty/netty-codec-haproxy/4.1.78.Final/netty-codec-haproxy-4.1.78.Final.jar
  100.0% [##########] 35.3 KiB (72.3 KiB / s)
https://nexus.celtra.com/repository/maven/com/twitter/finagle-netty4-http_2.12/22.12.1/finagle-netty4-http_2.12-22.12.1.jar
  100.0% [##########] 80.2 KiB (99.3 KiB / s)
https://nexus.celtra.com/repository/maven/com/twitter/finagle-base-http_2.12/22.12.1/finagle-base-http_2.12-22.12.1.jar
  100.0% [##########] 538.4 KiB (594.2 KiB / s)
https://nexus.celtra.com/repository/maven/com/twitter/finagle-netty4_2.12/22.12.1/finagle-netty4_2.12-22.12.1.jar
  100.0% [##########] 410.9 KiB (392.8 KiB / s)
https://nexus.celtra.com/repository/maven/com/twitter/finagle-core_2.12/22.12.1/finagle-core_2.12-22.12.1.jar
  100.0% [##########] 3.1 MiB (2.8 MiB / s)
https://nexus.celtra.com/repository/maven/com/twitter/finagle-http_2.12/22.12.1/finagle-http_2.12-22.12.1.jar
  100.0% [##########] 479.8 KiB (404.5 KiB / s)
[info] Fetched artifacts of 
```

**Pull request merged**
